<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Homepage</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>462ad56a-cb5d-4c20-ac72-1261f63047a0</testSuiteGuid>
   <testCaseLink>
      <guid>a5289262-83f9-407f-b831-ead890c9f731</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_HomeUrl</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>49d37d94-78e9-40f3-977a-298d058e9100</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_CategoriesCheck</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>abefde3c-ed60-4ab3-ab91-f0fcc07690f9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_ContactMessage</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>6998070e-21ff-4148-81be-c831c485db21</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DataMessage</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>6998070e-21ff-4148-81be-c831c485db21</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>8664f5ac-947c-4082-bda4-e3400a08abf8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6998070e-21ff-4148-81be-c831c485db21</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>name</value>
         <variableId>14bb62f7-a3fb-418d-a666-3303d8c42379</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6998070e-21ff-4148-81be-c831c485db21</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>message</value>
         <variableId>9744f209-1201-49c2-8118-cbe4474b6492</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
