<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ContactEmail</name>
   <tag></tag>
   <elementGuidId>86c9e588-9311-44ce-9b08-1d11de649733</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#recipient-email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='recipient-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fee60d8e-fed5-47e7-9c77-9d332d70d722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5fddbcb8-ece6-42c8-80a1-81db1980141e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2eff0312-f3cd-4b32-a6e5-69b96ea04c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>recipient-email</value>
      <webElementGuid>c1c6721f-8a30-43ac-aa1e-e142ae8644eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recipient-email&quot;)</value>
      <webElementGuid>00d33e0d-9fa7-4cec-b66d-ff6dd513ed74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='recipient-email']</value>
      <webElementGuid>18216f34-fb14-45b1-b08f-fd4871124e26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='exampleModal']/div/div/div[2]/form/div/input</value>
      <webElementGuid>2db774ad-6835-4d2e-9a4a-8443f32dbaf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>bf3cfad3-771f-4db8-ab5e-ae0dab9855ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'recipient-email']</value>
      <webElementGuid>e49c19f2-6747-4926-8ff3-2e72e563f4f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
